# Generated by Django 6.0.5 on 2026-05-13 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('estudantil', 'Estudantil'), ('sindical', 'Sindical'), ('associacao', 'Associação'), ('condominio', 'Condomínio'), ('conselho', 'Conselho'), ('outra', 'Outra')])),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('encerrada', 'Encerrada'), ('apurada', 'Apurada')], default='rascunho')),
                ('permite_branco', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Eleição',
                'verbose_name_plural': 'Eleições',
                'db_table': 'eleicao',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eleitor',
                'verbose_name_plural': 'Eleitores',
                'db_table': 'eleitores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('nome_urna', models.CharField(max_length=50)),
                ('partido_ou_chapa', models.CharField(blank=True, max_length=100)),
                ('proposta', models.TextField(blank=True)),
                ('foto_url', models.URLField(blank=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='urna.eleicao')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidato',
                'ordering': ['nome'],
                'unique_together': {('eleicao', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='eleicao',
            name='criada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleicoes_criadas', to='urna.eleitor'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_branco', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('comprovante_hash', models.CharField(max_length=64, unique=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.candidato')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.eleicao')),
            ],
        ),
        migrations.CreateModel(
            name='AptidaoEleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptos', to='urna.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aptidoes', to='urna.eleitor')),
            ],
            options={
                'db_table': 'aptidao_eleitor',
                'ordering': ['eleicao'],
                'unique_together': {('eleitor', 'eleicao')},
            },
        ),
        migrations.CreateModel(
            name='RegistroVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_votacao', to='urna.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_votacao', to='urna.eleitor')),
            ],
            options={
                'db_table': 'registro_votacao',
                'ordering': ['-data_hora'],
                'unique_together': {('eleitor', 'eleicao')},
            },
        ),
    ]
